[workspace]
resolver="2"

members = [
    "packages/backend-next",
    "packages/catlog",
    "packages/catlog-wasm",
]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
