[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.7"
rspc = "0.2.0"
rspc-axum = "0.1.1"
socketioxide = "0.14.1"
specta = { version = "1.0.5", features = ["uuid"] }
tokio = { version = "1.40.0", features = ["full"] }
uuid = { version = "1.10.0", features = ["v7", "serde"] }
